export const EnKey = 'EN';
export const EnData = {
    "Details": "Show details",
    "EN": "English",
    "HE": "Hebrew",
    "Ok": "OK",
    "Registration": "Registration",
    "AmountStudentRegistration":"Amount Student Registration",
    "RegristationPaperFor": "Regristation paper for",
    "Name": "First name",
    "LastName": "Last name",
    "Address": "Address",
    "Phone": "Phone",
    "Tz": "Tz",
    "Mail": "Email",
    "CreditNum": "cradit num",
    "ThreeDigit": "three digit of credit back",
    "EndDate": "End date",
    "TzOf": "Tz of credit husband",
    "Open": "Open cours",
    "Sunday": "Sunday",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thursday": "Thursday",
    "Subject": "Course subject ",
    "Day": "Day in week",
    "Continue": "Continue",
    "Teacher": "Name teacher",
    "ShowCourses": "Show courses",
    "ShowTeachers": "Show teachers",
    "ShowStudents": "Show students",
    "Id": "Id",
    "Edit": "Edit",
    "Delete": "Delete",
    "Create": "Create new",
    "Credit": "Credit Number",
    "ExpiryDate": "ExpiryDate",
    "NameCourse": "Name course",
    "FromHourC": "From hour",
    "UntilHourC": "Until hour",
    "MinStudents": "Minimum students",
    "MaxStudents": "Maximum students",
    "AmountHour": "Amount hour",
    "Price": "Price per hour",
    "OpenCourse": "Open?",
    "IdTypeCourse": "id type course",
    "Search": "Search",
    "HomePage": "Home Page",
    "MainMenu": "Main Menu",
    "DayInWeek": "Day",
    "PricePerHour": "Price per hour",
    "TeacherName": "Teacher name",
    "Prefer": "Prefer",
    "hidden": "hidden",
    "Courses": "Courses",
    "contact1": "Contact us with any request, comment or enlightenment",
    // "contact2": "  'משרד ראשי: בריכת 'קרן אור",
    // "contact11": "אבא הלל סילבר 3, רמות א ירושלים",
    "contact3": "Tel: 052-7170595, 052-5403999",
    "contact4": "Fax: 025004970",
    "contact5":"Mail: sitefurthertraining@gmail.com",
    "contact6": "You can leave details and we will contact you",
    "contact7":"Full Name",
    "contact8": "Phone",
    "contact9": "Mail",
    "contact10":"Question",
    "send": "Send",
    "Contact":"Contact Us",
    "Personal":"Personal",
    "put":"Put",
    "connect":"connect",
    "password":"password",
    "editDetails":"Edit details",
    "forgetPassword":"fogot password",
    "DisplayError":"You already connected, please connect by login",
    "DisplayErrorNewConnect":"You are not registered to the site, you have to register as a new user",
    "errorEditDetails":"you have to register to the site before",
    "ConfirmDeleteStudent":"Are you sure you want to delete this student?",
    "ConfirmDeleteCourse":"Are you sure you want to delete this course?",
    "ConfirmDeleteTeacher":"Are you sure you want to delete this teacher?",
    "ConfirmDeleteSubject":"Are you sure you want to delete this subject?",
    "ConfirmDeleteRegistration":"Are you sure you want to delete this registration?",
    "CANCEL":"CANCEL",
    "OK":"OK",
    "Teachers":"Teachers",
    "Students":"Students",
    "EditCourse":"Edit course",
    "CreateCourse":"Create course",
    "EditTeacher":"Edit teacher",
    "CreateTeacher":"Create teacher",
    "EditStudent":"Edit course",
    "CreateStudent":"Create student",
    "Hello":"Hello",
    "Surveys":"Surveys",
    "About":"About",
    "contact":"contact",
    "ErrorDeleteTeacher":"This teacher cannot be deleted because it is embedded in courses. If you want to delete you need to embed another teacher in these courses",
    "differentSubject":"differentSubject",
    "FatherSubject":"category",
    "MinStudent":"Min student",
    "ShowSubjects":"Show subjects",
    "CourseExplainText":"Course explain",
    "Picture":"Picture",
    "IdFatherSubject":"Id father subject",
    "CreateSubject":"Subject create",
    "EditSubject":"Subject edit",
    "errorDeleteCategoryText":"You cannot remove this subject because there are sub-subjects in this category",
   "IdCourse":"Id course",
   "RegistrationDate":"Registration date",
   "RegistrationTbl":"Registration",
   "ShowRegistration":"Show registration"
}