export const HeKey='HE';
export const HeData={
    "Details":"הצג פרטים",
    "EN":"אנגלית",
    "HE":"עברית",
    "Ok":"אישור",
    "Registration":"לרישום",
    "AmountStudentRegistration":"מספר נרשמות",
    "RegristationPaperFor":" דף רישום ל",
    "Name":"שם פרטי",
    "LastName":"שם משפחה",
    "Address":"כתובת",
    "Phone":"נייד",
    "Tz":"ת.ז",
    "Mail":"מייל",
    "CreditNum":"מספר אשראי",
    "ThreeDigit":"3 ספרות בגב הכרטיס",
    "ExpiryDate":"תוקף",
    "TzOf":"תעודת זהות של בעל הכרטיס",
    "Open":"פתיחת קורס",
    "Sunday":"ראשון",
    "Monday":"שני",
    "Tuesday":"שלישי",
    "Wednesday":"רביעי",
    "Thursday":"חמישי",
    "Subject":"נושא הקורס",
    "Day":"יום בשבוע",
    "Continue":"המשך",
    "Teacher":"מורה",
    "ShowCourses":"רשימת קורסים",
    "ShowTeachers":"רשימת מרצים",
    "ShowStudents":"רשימת סטודנטים",
    "Id":"קוד",
    "Edit":"ערוך",
    "Delete":"מחק",
    "Create":"צור חדש",
    "Credit":"מספר כ.אשראי",
    "NameCourse":"שם קורס",
    "FromHourC":"משעה",
    "UntilHourC":"עד שעה",
    "MinStudents":"מינימום תלמידות",
    "MaxStudents":"מקסימום תלמידות",
    "AmountHour":"מספר שעות",
    "Price":"מחיר לשעה",
    "OpenCourse":"נפתח?",
    "IdTypeCourse":"סוג קורס",
    "Search":"חיפוש",
    "HomePage":"דף הבית",
    "MainMenu":"תפריט",
    "DayInWeek":"יום",
    "PricePerHour":"מחיר לשעה",
    "TeacherName":"שם מורה",
    "Prefer":"עדיפות",
    "hidden":"הסתר",
    "Courses":"קורסים",
    "contact1": "על כל בקשה, הערה או הארה צרו עמנו קשר",
    // "contact2": "  'משרד ראשי: בריכת 'קרן אור",
    // "contact11": "אבא הלל סילבר 3, רמות א ירושלים",
    "contact3": "טל: 052-7170595   ,  052-5403999",
    "contact4": "פקס:  025004970",
    "contact5":"מייל:  sitefurthertraining@gmail.com",
    "contact6": "ניתן להשאיר פרטים ואנו ניצור אתכם קשר",
    "contact7": "שם מלא",
    "contact8": "טלפון",
    "contact9": "מייל",
    "contact10": "שאלה/הערה/בקשה",
    "send": "שלח",
    "Contact":"צור קשר",
    "Personal":"אזור אישי",
    "put":"הכנס",
    "connect":"התחבר",
    "password":"סיסמא",
    "editDetails":"ערוך פרטים",
    "forgetPassword":"שכחתי סיסמא",
    "DisplayError":"הנך רשום כבר לאתר, יש להכנס באמצעות כניסה מקוצרת(מייל וסיסמא)",
    "DisplayErrorNewConnect":"אינך רשום לאתר, יש להרשם כמשתמש חדש",
    "errorEditDetails":"יש להרשם קודם לאתר",
    "ConfirmDeleteStudent":"האם את/ה בטוח/ה שברצונך למחוק סטודנט זו?",
    "ConfirmDeleteCourse":"האם את/ה בטוח/ה שברצונך למחוק קורס זהּ?",
    "ConfirmDeleteTeacher":"האם את/ה בטוח/ה שברצונך למחוק מורה זו?",
    "ConfirmDeleteSubject":"האם את/ה בטוח/ה שברצונך למחוק נושא זה?",
    "ConfirmDeleteRegistration":"האם את/ה בטוח/ה שברצונך למחוק רישום זה?",    
    "CANCEL":"ביטול",
    "OK":"אישור",
    "Teachers":"מרצים",
    "Students":"סטודנטים",
    "EditCourse":"עריכת קורס",
    "CreateCourse":"יצירת קורס חדש",
    "EditTeacher":"עריכת מורה",
    "CreateTeacher":"יצירת מורה חדשה",
    "EditStudent":"עריכת סטודנטית",
    "CreateStudent":"יצירת סטודנטית חדשה",
    "Hello":"שלום",
    "Surveys":"סיקור",
    "About":"אודות",
    "contact":"צור קשר",
    "ErrorDeleteTeacher":"אין אפשרות למחוק מורה זו מכיוון שהיא משובצת בקורסים. אם ברצונך למחוק עליך לשבץ מורה אחרת בקורסים אלו",
    "differentSubject":"אחר",
    "FatherSubject":"קטגוריה",
    "MinStudent":"מינימום תלמידות",
    "ShowSubjects":"רשימת נושאי הקורסים",
    "CourseExplainText":"פרוט על הקורס",
    "Picture":"תמונה",
    "IdFatherSubject":"קוד אב נושא",
    "CreateSubject":"יצירת נושא",
    "EditSubject":"עריכת נושא",
    "errorDeleteCategoryText":"אין באפשרותך למחוק נושא זה כיוון שישנם תתי נושאים תחת קטגוריה זו",
    "IdCourse":"מס' קורס",
    "RegistrationDate":"תאריך רישום",
    "RegistrationTbl":"רישום",
    "ShowRegistration":"רישום לקורסים"
}
